language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t riteshvaryani/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true riteshvaryani/react-test npm test

after_success:
    - docker build -t riteshvaryani/multi-client ./client
    - docker build -t riteshvaryani/multi-server ./server
    - docker build -t riteshvaryani/multi-nginx ./nginx
    - docker build -t riteshvaryani/multi-worker ./worker
# Login to docker-cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push to docker-cli
    - docker push riteshvaryani/multi-client
    - docker push riteshvaryani/multi-server
    - docker push riteshvaryani/multi-nginx
    - docker push riteshvaryani/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-839277666105
    bucket_path: docker-multi
    on:
        branch:  master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY